# Generated by Django 3.1.1 on 2020-10-13 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
